#pragma once

#define PRINTF_DISABLE_SUPPORT_LONG_LONG    1
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T    1
#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL  1
#define PRINTF_DISABLE_SUPPORT_FLOAT        1// TODO:添加对printf的支持


